version: '3.1'

services:
  localstack:
    image:  localstack/localstack:latest
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=docker
    ports:  
      - "4566-4597:4566-4597"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
