service: z5-layers

custom:
  stage: ${opt:stage, opt:stage, 'local'}
  region: ${file(./../../env.${opt:stage, opt:stage, 'local'}.json):AWS_REGION}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - '*'
      Resource:
        - '*'

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}

layers:
  base-handler:
    name: base-handler-${self:custom.stage}
    path: ./../../built/shared/base-handler
